services:
  db:
    image: postgres:17
    container_name: postgres
    environment:
      POSTGRES_DB: passwordmanager
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d passwordmanager"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    environment:
      DB_URL: jdbc:postgresql://db:5432/passwordmanager
      DB_USER: admin
      DB_PASSWORD: secret
    ports:
      - "8080:8080"
    volumes:
      - ./backend/src:/app/src
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data: